apiVersion: v2
name: api-gateway-api
description: A Helm chart for the API Gateway API
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: mysql
    version: 8.8.23
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled