## Configure the ConfigMap resource that allows you to store non-confidential data in key-value pairs.
##
configMap:
  data:
    config.yaml:
      keycloak:
        credentials:
          url: "https://acc-login.company.info/auth"
          realm: servicesv2
          clientID: temporal-provisioning
          clientSecret: 2rgkbgTanrw7OJFxU0qHs90WIap2iaDj
          pageSize: 50
        briefRepresentation: false
        first: 0
        max: 500
      tyk:
        url: http://acc-tyk-gateway.tyk-402:9696
        secret: a7BLAktwAFZH2UvTJveRcxtxEGsHTdB3ZuervmtppmD529ZwSTFBaByC4rgXdVHxfxp5UCLaK9CkYU9jRr3ENF9SpkAPVswuSxd32VxBdE3rsbH88ApYQSa2xxuh9hQw
        debug: true