## Configure the ConfigMap resource that allows you to store non-confidential data in key-value pairs.
##
configMap:
  data:
    config.yaml:
      tyk:
        endpoint: "acc-tyk-gateway.tyk-402:9696"
      database:
        host: "acc-postgresql-12-cluster.cluster-ct6gy97ncd1k.eu-west-1.rds.amazonaws.com"
