## Helmet (App) image version
##
image:
  registry: registry.ci.fdmg.org
  repository: ci-api/admin-api
  pullSecrets:
    - gitlab-registry

sidecars:
  - name: opa
    image: openpolicyagent/opa:0.54.0
    ports:
      - name: http
        containerPort: 8181
    args:
      - "run"
      - "--ignore=.*"  # exclude hidden dirs created by Kubernetes
      - "--server"
      - "--h2c"
      - "-c"
      - "/opa_config.yaml"
    livenessProbe:
      httpGet:
        path: /health?bundle=true
        scheme: HTTP
        port: 8181
      initialDelaySeconds: 5
      periodSeconds: 30
    readinessProbe:
      httpGet:
        path: /health?bundle=true  # Include bundle activation in readiness
        scheme: HTTP
        port: 8181
      initialDelaySeconds: 5
      periodSeconds: 30
    volumeMounts:
      - readOnly: true
        mountPath: /opa_config.yaml
        subPath: opa_config.yaml
        name: opa-config

# sidecar volume
extraVolumes:
  - name: opa-config
    configMap:
      name: "{{ .Release.Name }}"
      items:
        - key: opa_config.yaml
          path: opa_config.yaml

## Configure extra options for liveness probe
##
livenessProbe:
  enabled: true
  httpGet:
    path: /livez
    port: http

## Configure extra options for readiness probe
##
readinessProbe:
  enabled: true
  httpGet:
    path: /readyz
    port: http

## Configure the ingress resource that allows you to access the
## APP installation. Set up the URL
##
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"

## Prometheus Operator ServiceMonitor configuration
##
serviceMonitor:
  labels:
    prometheus: kube-prometheus

## APP's resource requests and limits
##
resources:
  limits:
    cpu: 500m
    memory: 800Mi
  requests:
    cpu: 250m
    memory: 400Mi

## Configure the ConfigMap resource that allows you to store non-confidential data in key-value pairs.
##
configMap:
  mounted: true
  mountPath: "/config.yaml"
  subPath: "config.yaml"
  data:
    config.yaml:
      host: "0.0.0.0"
      port: "8080"
      logLevel: "debug"
      tyk:
        scheme: "http"
        endpoint: "agw-api-tyk:8081"
        debug: "true"
        secret: "secret"
      database:
        host: "localhost"
        port: "5432"
        username: "key-management-api"
        password: "password"
        name: "key_management"
      temporal:
        hostPort: "{{ .Values.global.temporal.hostPort }}"
        namespace: "ci-api"
      oma:
        address:
        namespace: "ci-api"
        opa:
          address: http://localhost:8181
      solvimon:
        baseUrl: https://test.api.solvimon.com/v1
        apiKey: supersecretkey
      pricingPlans:
        small:
          quota: small
          numberOfAPIProductionKeys: 1
          numberOfAPISandboxKeys: 1
        medium:
          quota: medium
          numberOfAPIProductionKeys: 3
          numberOfAPISandboxKeys: 1
      publisher:
        enabled: false
        eventBusName: ""
        emailRecipient: "support-ws@company.info"
        aws:
          region: "eu-west-1"
    opa_config.yaml:
      services:
        - name: oma
          url:
      bundles:
        authz:
          service: oma
          resource: /namespaces/ci-api/bundles/admin/api
          polling:
            long_polling_timeout_seconds: 10

postgresql:
  enabled: false
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 12.9.0
  architecture: standalone
  global:
    postgresql:
      auth:
        postgresPassword: "root"
        username: key-management-api
        password: "password"
        database: key_management
  primary:
    persistence:
      enabled: false
    initdb:
      scripts:
        initialize.sql: |
          CREATE EXTENSION btree_gin;
          CREATE TYPE apikey_environment AS ENUM ('production', 'sandbox');
          CREATE TABLE IF NOT EXISTS api_keys
          (
              id            VARCHAR(26) PRIMARY KEY NOT NULL,
              actor_id      VARCHAR(250)            NOT NULL,
              creator_id    VARCHAR(250),
              key_hash      VARCHAR(32)             NOT NULL,
              expires_at    date                    NULL,
              creation_date TIMESTAMP                        DEFAULT NOW() NOT NULL,
              last_modified TIMESTAMP                        DEFAULT NOW() NOT NULL,
              description   TEXT                             DEFAULT NULL,
              deleted_at    TIMESTAMP                        DEFAULT NULL,
              contacts      JSONB                   NOT NULL DEFAULT '{}'::JSONB,
              active        BOOLEAN                 NOT NULL DEFAULT TRUE,
              metadata      JSONB                   NOT NULL DEFAULT '{}'::JSONB,
              environment   apikey_environment      NOT NULL,
              labels        JSONB                   NOT NULL DEFAULT '{}'::JSONB
          );
          CREATE INDEX IF NOT EXISTS api_keys_description_key ON api_keys USING GIN (description);
  readReplicas:
    persistence:
      enabled: false

## @param envVars Extra environment variables to be set on APP container
##
envVars:
  - name: CONSUL_HTTP_ADDR
    value: "{{ .Values.global.consul.host }}"
  - name: CONSUL_HTTP_TOKEN
    value: "{{ .Values.global.consul.token }}"
  - name: CONSUL_APP_KEY
    value: "{{ .Values.global.consul.app_key }}"
  - name: CONSUL_PRICING_PLANS_KEY
    value: "{{ .Values.global.consul.pricing_plans_key }}"

serviceAccount:
  create: true