## Configure the ConfigMap resource that allows you to store non-confidential data in key-value pairs.
##
configMap:
  data:
    config.yaml:
      app:
        keycloak:
          url: "https://acc-login.company.info/auth"
