## Configure the ConfigMap resource that allows you to store non-confidential data in key-value pairs.
##
configMap:
  data:
    config.yaml:
      app:
        database:
          host: "{{ .Release.Name }}-postgresql"
          port: "5432"
          username: "{{ .Values.postgresql.global.postgresql.auth.username }}"
          password: "{{ .Values.postgresql.global.postgresql.auth.password }}"
          name: "{{ .Values.postgresql.global.postgresql.auth.database }}"
        temporal:
          hostPort: "{{ .Values.global.temporal.hostPort }}"
          namespace: "{{ .Values.global.temporal.namespace }}"
    opa_config.yaml:
      services:
        - name: oma
          url: "http://acc-oma.oma-4624/v1"

# sidecar volume
extraVolumes:
  - name: opa-config
    configMap:
      name: "{{ .Release.Name }}-admin-api"
      items:
        - key: opa_config.yaml
          path: opa_config.yaml

postgresql:
  enabled: true
