image:
  repository: registry.ci.fdmg.org/datacluster/nl/api_2.0/tyk-api-key-manager
  pullPolicy: Always
  tag: "latest"

replicaCount: 1

imagePullSecrets:
  - name: gitlab-registry

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  path: /
  pathType: ImplementationSpecific
  annotations: {}
  hosts: []
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  application:
    host: "0.0.0.0"
    port: "80"
    logLevel: "debug"
  tyk:
    scheme: "http"
    endpoint: "agw-api-tyk:8081"
    debug: "true"
    secret: "secret"

serviceMonitor:
  enabled: false
  interval: 60s
  scrapeTimeout: 10s
