include:
  - project: 'datacluster/gitlab-templates'
    file: 'golang-templates.yaml'

variables:
  GO_VERSION: "1.17"
  GO_BUILD_MAIN_PKG: "./cmd/api"
  SWAGGER_VALIDATE_DISABLED: "true"
  SWAGGER_VALIDATE_SWAGGER_SPEC: "swagger.yaml"
  AUTO_DEVOPS_CHART: "nexus/api-gateway-api"

  # temporary hard-coded policy for the pipeline
  HELM_DEFAULTS: "
    --set image.tag=$${IMAGE_TAG} \
    --set ingress.hosts[0].host=$${HOST} \
    --set ingress.hosts[0].paths[0].path=/ \
    --set ingress.hosts[0].paths[0].pathType=Prefix \
    --set ingress.tls[0].hosts[0]=$${HOST} \
    --set ingress.tls[0].secretName=${KUBE_INGRESS_TLS_DEFAULT_SECRET_NAME} \
    --set config.tyk.policies[0]=compliance-full-access-policy \
    --set config.tyk.policies[1]=routeplanner-full-access-policy \
    --set config.tyk.policies[2]=international-business-full \
    --set config.tyk.policies[3]=dutchbusiness-full-access-policy \
    --set config.tyk.policies[4]=marketing-intelligence-full-access-policy \
    --set config.tyk.policies[5]=ci-api-full \
    --set config.tyk.policies[6]=credit-api-access-policy \
  "

  HELM_TESTING_VARIABLES: "
    --set mysql.enabled=true \
    --set mysql.initdbScriptsConfigMap=test-$CI_COMMIT_REF_SLUG-config-mysql \
    --set config.database.address=test-$CI_COMMIT_REF_SLUG-mysql:3306 \
    --set mysql.fullnameOverride=test-$CI_COMMIT_REF_SLUG-mysql \
  "

  HELM_ACC_VARIABLES: "
    --set mysql.enabled=false \
    --set ingress.enabled=true \
    --set serviceMonitor.enabled=true \
    --set tolerations[0].key=namespace \
    --set tolerations[0].operator=Equal \
    --set tolerations[0].value=acc \
    --set tolerations[0].effect=NoSchedule \
    --set nodeSelector.\"kubernetes\\.ci\\.fdmg\\.org/nodegroup\"=acc \
    --set config.tyk.endpoint=\"acc-tyk-gateway.tyk-402:9696\" \
    --set config.tyk.secret=\"a7BLAktwAFZH2UvTJveRcxtxEGsHTdB3ZuervmtppmD529ZwSTFBaByC4rgXdVHxfxp5UCLaK9CkYU9jRr3ENF9SpkAPVswuSxd32VxBdE3rsbH88ApYQSa2xxuh9hQw\" \
    --set config.database.address=\"${DATABASE_HOST_ACC}\" \
    --set config.database.username=\"${DATABASE_USER_ACC}\" \
    --set config.database.password=\"${DATABASE_PASSWORD_ACC}\" \
    --set config.database.name=\"${DATABASE_NAME_ACC}\" \
  "

  HELM_PROD_VARIABLES: "
    --set mysql.enabled=false \
    --set replicaCount=3 
    --set ingress.enabled=true \
    --set serviceMonitor.enabled=true \
    --set tolerations[0].key=namespace \
    --set tolerations[0].operator=Equal \
    --set tolerations[0].value=prod \
    --set tolerations[0].effect=NoSchedule \
    --set nodeSelector.\"kubernetes\\.ci\\.fdmg\\.org/nodegroup\"=prod \
    --set config.tyk.endpoint=\"prod-tyk-gateway.tyk-402:9696\" \
    --set config.tyk.secret=\"8GbU4fky7XB2QGsdwssuHRtWyH6szJjssRdj97yuxTjYSkaDPwQV8nwAALHfHV5f5sjk6jYEJxzkmUyfBX8j6MJgrGSannnxargJaMMEtfVDkfjcNZfq4DymHsfJ9r3E\" \
    --set config.database.address=\"${DATABASE_HOST_PROD}\" \
    --set config.database.username=\"${DATABASE_USER_PROD}\" \
    --set config.database.password=\"${DATABASE_PASSWORD_PROD}\" \
    --set config.database.name=\"${DATABASE_NAME_PROD}\" \
  "


