include:
  - project: 'datacluster/gitlab-templates'
    file: 'golang-templates.yaml'

variables:
  GO_VERSION: "1.19"
  GO_BUILD_MAIN_PKG: "./cmd/api"
  SWAGGER_VALIDATE_DISABLED: "true"
  SWAGGER_VALIDATE_SWAGGER_SPEC: "swagger.yaml"
  HELM_GLOBAL_VARIABLES: "
    --set configMap.data.\"config\\.yaml\".tyk.secret=\"${TYK_SECRET}\" \
    --set configMap.data.\"config\\.yaml\".database.username=\"${DATABASE_USER}\" \
    --set configMap.data.\"config\\.yaml\".database.password=\"${DATABASE_PASSWORD}\" \
  "

deploy:testing:
  variables:
    HELM_GLOBAL_VARIABLES: ""
  environment:
    name: nl/test/$CI_COMMIT_REF_NAME

destroy:testing:
  environment:
    name: nl/test/$CI_COMMIT_REF_NAME

deploy:testing:de:
  extends: deploy:testing
  variables:
    HELM_GLOBAL_VARIABLES: ""
  environment:
    name: de/test/$CI_COMMIT_REF_NAME
    on_stop: destroy:testing:de

destroy:testing:de:
  extends: destroy:testing
  environment:
    name: de/test/$CI_COMMIT_REF_NAME

deploy:acceptance:
  environment:
    name: nl/acc

deploy:acceptance:de:
  extends: deploy:acceptance
  environment:
    name: de/acc

deploy:production:
  extends: .deploy-template
  environment:
    name: nl/prod

deploy:production:de:
  extends: deploy:production
  environment:
    name: de/prod
