# golangci-lint configuration (HARD/REQUIRED checks)
# This config contains only critical linters that must pass.
# For optional quality checks, see .golangci-soft.yaml
version: "2"

linters:
  enable:
    # === SECURITY ===
    # bidichk: Detects dangerous Unicode bidirectional text (security)
    # Prevents invisible characters that can hide malicious code
    - bidichk

    # gosec: Security vulnerability scanner
    # Detects SQL injection, hardcoded creds, path traversal, bad TLS, etc.
    - gosec

    # === CRITICAL BUGS ===
    # errcheck: Ensures errors are checked (critical bugs)
    # BAD:  file.Close()
    # GOOD: if err := file.Close(); err != nil { return err }
    - errcheck

    # nilnesserr: Enhanced nilerr - catches complex nil/error mismatches
    # BAD:  if err != nil { return nil, differentErr }
    # GOOD: if err != nil { return nil, err }
    - nilnesserr

    # nilnil: Catches returning nil error with nil/invalid value
    # BAD:  func GetUser(id int) (*User, error) { return nil, nil }
    # GOOD: func GetUser(id int) (*User, error) { return nil, ErrNotFound }
    - nilnil

    # staticcheck: The gold standard Go linter (has autofix)
    # Catches 100+ bug patterns, style issues, and simplifications
    - staticcheck

    # govet: Standard Go vet checks (extended)
    # Catches printf errors, mutex copies, struct tag issues, shadowing, etc.
    - govet

    # bodyclose: Ensures HTTP response bodies are closed (resource leaks)
    # BAD:  resp, _ := http.Get(url); return resp.StatusCode
    # GOOD: resp, _ := http.Get(url); defer resp.Body.Close()
    - bodyclose

    # forcetypeassert: Catches unsafe type assertions that can panic
    # BAD:  s := v.(string)           // panics if v is not string
    # GOOD: s, ok := v.(string); if !ok { return err }
    - forcetypeassert

    # === CORRECTNESS ===
    # errorlint: Ensures proper Go 1.13+ error handling
    # BAD:  if err == ErrNotFound { }        // breaks with wrapped errors
    # GOOD: if errors.Is(err, ErrNotFound) { }
    - errorlint

    # contextcheck: Ensures context is properly propagated
    # BAD:  func Handle(ctx context.Context) { doWork(context.Background()) }
    # GOOD: func Handle(ctx context.Context) { doWork(ctx) }
    - contextcheck

    # fatcontext: Detects nested contexts in loops (memory leak)
    # BAD:  for _, item := range items { ctx = context.WithValue(ctx, k, item) }
    # GOOD: for _, item := range items { itemCtx := context.WithValue(ctx, k, item) }
    - fatcontext

    # spancheck: Validates OpenTelemetry span handling
    # BAD:  span := tracer.Start(ctx, "op"); /* no span.End() */
    # GOOD: defer span.End(); span.RecordError(err); span.SetStatus(codes.Error)
    - spancheck

    # durationcheck: Catches duration * duration bugs
    # BAD:  timeout := time.Second * time.Second  // nonsense: 1e18 ns!
    # GOOD: timeout := 5 * time.Second
    - durationcheck

    # makezero: Catches slice initialization bugs
    # BAD:  s := make([]int, 5); s = append(s, 1)  // s has 6 elements, not 1!
    # GOOD: s := make([]int, 0, 5); s = append(s, 1)
    - makezero

    # reassign: Prevents reassignment of package-level variables
    # BAD:  io.EOF = errors.New("custom")  // breaks all io.EOF checks!
    # GOOD: Don't reassign package variables
    - reassign

  settings:
    bidichk:
      # All Unicode bidirectional overrides are dangerous - check all
      left-to-right-embedding: true
      right-to-left-embedding: true
      pop-directional-formatting: true
      left-to-right-override: true
      right-to-left-override: true
      left-to-right-isolate: true
      right-to-left-isolate: true
      first-strong-isolate: true
      pop-directional-isolate: true

    errcheck:
      # Check type assertions: a := b.(Type) can panic if wrong
      check-type-assertions: true
      # Check blank assignments: _, _ = funcReturningError()
      check-blank: true
      # Don't exclude common functions - be thorough
      disable-default-exclusions: false
      exclude-functions: []
      verbose: true

    errorlint:
      # Check fmt.Errorf uses %w for wrapping (preserves error chain)
      errorf: true
      # Check type assertions use errors.As instead of type assertion
      asserts: true
      # Check comparisons use errors.Is instead of ==
      comparison: true

    fatcontext:
      # Check struct pointers for context accumulation
      check-struct-pointers: false

    gosec:
      # Filter by severity (low, medium, high)
      severity: medium
      # Filter by confidence (low, medium, high)
      confidence: medium

    govet:
      enable:
        # Variable shadowing detection
        - shadow
        # Nil pointer dereference checks
        - nilness
        # Unused writes detection
        - unusedwrite
      settings:
        shadow:
          # Strict shadowing checks
          strict: true

    makezero:
      # Strict mode: only allow make([]T, 0) or make([]T, 0, cap)
      always: true

    nilnil:
      # Also catch: return validValue, someError (opposite problem)
      detect-opposite: true

    reassign:
      # Check ALL package variables
      patterns:
        - ".*"

    spancheck:
      checks:
        # Ensure span.End() is called (usually via defer)
        - end
        # Ensure span.RecordError(err) when returning error
        - record-error
        # Ensure span.SetStatus(codes.Error, msg) when returning error
        - set-status

    staticcheck:
      # Enable all checks (SA*, S*, ST*, QF*)
      checks: ["all"]

formatters:
  enable:
    # gofumpt: Stricter gofmt with additional consistency rules
    - gofumpt

    # gci: Import statement organization with granular control
    - gci

  settings:
    gofumpt:
      # Module path for determining local imports
      module-path: rivaas.dev
      # Enable additional formatting rules beyond gofmt
      extra-rules: true

    gci:
      # Import section order
      sections:
        - standard                    # Standard library packages
        - default                     # Third-party packages
        - prefix(rivaas.dev)          # All rivaas.dev/* local modules
        - blank                       # Blank imports (side effects)
        - alias                       # Aliased imports
      custom-order: true
      no-inline-comments: true
      no-prefix-comments: true

issues:
  # Report all critical issues
  max-issues-per-linter: 0
  max-same-issues: 0
  # Don't auto-fix by default (CI should detect, not modify)
  fix: false

run:
  # Timeout for total work
  timeout: 5m
