app:
  host: 0.0.0.0
  port: 8090
  logLevel: "debug"

  database:
    host: 127.0.0.1
    port: 5432
    username: user
    password: secret
    name: admin_api

  tyk:
    url: http://127.0.0.1:8081
    secret: secret
    debug: true

  temporal:
    hostPort: 127.0.0.1:7233
    namespace: default

  keycloak:
    url: http://localhost:8080
    realm: master
    clientID: admin-cli
    clientSecret: Asbc6VAmt7AqFCLDorGSYoazk6nKhwKx
    pageSize: 5

  oma:
    address: http://oma-acc.nl.ci.fdmg.org
    namespace: ci-api
    opa:
      address: http://localhost:8282
