application:
  host: "0.0.0.0"
  port: "8080"
  logLevel: "debug"

tyk:
  scheme: "http"
  endpoint: "agw-api-tyk:8081"
  debug: "false"
  secret: "secret"
  policies:
    - "compliance-monitor-full-access"
    - "routeplanner-full-access"
