app:
  host: 0.0.0.0
  port: 8090
  logLevel: "debug"

  database:
    host: 127.0.0.1
    port: 5432
    username: user
    password: secret
    name: admin_api

  tyk:
    url: http://127.0.0.1:8081
    secret: secret
    debug: true

  temporal:
    hostPort: 127.0.0.1:7233
    namespace: default

  keycloak:
    credentials:
      url: http://localhost:8080
      realm: master
      clientID: admin-cli
      clientSecret: dXXvgDaFYaybUXsVXECqw7p1sceqYAGQ
      pageSize: 5
    briefRepresentation: false
    first: 0
    max: 500

  oma:
    address: http://oma-acc.nl.ci.fdmg.org
    namespace: ci-api
    opa:
      address: http://localhost:8282

  openTelemetry:
    url: "http://localhost:14268/api/traces"
