swagger: '2.0'
info:
  version: 1.0.0
  title: API Gateway API
  description: |
    This is where you can manage API Gateway using APIs
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/hal+json
  - application/problem+json
tags:
  - name: key
    description: Calls related to API keys
paths:
  /keys:
    get:
      operationId: list_keys
      tags:
        - keys
      description: |
        List API Keys
      consumes:
        - application/json
      parameters:
        - in: query
          name: actor_id
          description: The actor id to filter on
          type: string
          required: false
        - in: query
          name: description
          description: The description term to fuzzy match on
          type: string
          required: false
      responses:
        '200':
          description: List of key hashes, optionally per actor
          schema:
            type: array
            items:
              type: object
              description: A key
              $ref: "#/definitions/KeyDetails"
        '500':
          $ref: "#/responses/InternalServerError"
    post:
      operationId: create_key
      tags:
        - keys
      description: |
        Create a new API key
      consumes:
        - application/json
      parameters:
        - in: body
          name: request
          description: The details of the key being created.
          schema:
            type: object
            required:
              - actor_id
            properties:
              policies:
                type: array
                description: The access policies to give, leave empty for none
                items:
                  type: string
              actor_id:
                type: string
                description: The reference to the actor. In simple words, this is what binds an API key to a user/customer.
                pattern: '^.{1,16}'
              expiration_date:
                type: string
                description: Date on which the api key will expire at 00.00 (optional)
                format: date
                pattern: '^\d{4}\-\d{2}-\d{2}'
              quota:
                type: integer
                description: The amount of calls the API Key can make (optional)
              description:
                type: string
                description: Description for the key (optional)
                maxLength: 64
      responses:
        '201':
          description: An API key has been created
          schema:
            allOf:
              - type: object
                description: A key
                $ref: "#/definitions/KeyCredentials"
        '400':
          $ref: "#/responses/BadRequest"
        '500':
          $ref: "#/responses/InternalServerError"
  /keys/{key_hash}:
    get:
      operationId: get_key
      tags:
        - keys
      description: |
        Get an api key
      consumes:
        - application/json
      parameters:
        - in: path
          name: key_hash
          description: The key hash
          type: string
          required: true
      responses:
        '200':
          description: Detailed properties of a key
          schema:
              $ref: '#/definitions/KeyDetailsWithGatewayContext'
        '400':
          $ref: "#/responses/BadRequest"
        '404':
          $ref: "#/responses/NotFound"
        '500':
          $ref: "#/responses/InternalServerError"
  /policies:
    get:
      operationId: list_policies
      tags:
        - policy
      description: |
        Get the list of available policies
      consumes:
        - application/json
      parameters: []
      responses:
        '200':
          description: list of available policies
          schema:
              type: array
              items:
                type: string
              example: ["compliance-monitor-full-access", "routeplanner-full-access"]
responses:
  NotFound:
    description: NotFound
    schema:
      $ref: "https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Problem.json#/definitions/Problem"
  BadRequest:
    description: Bad Request
    schema:
      $ref: "https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Problem.json#/definitions/Problem"
  InternalServerError:
    description: Internal Server Error
    schema:
      $ref: "https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Problem.json#/definitions/Problem"
definitions:
  KeyCredentials:
    title: KeyCredentials
    description: API key credentials
    type: object
    allOf:
      - properties:
          key:
            type: string
            description: The created API key which can be used to access APIs.
          hash:
            type: string
            description: The key hash. This is a unique identifier to each API key.
        required: [ "key", "hash" ]
  KeyDetails:
    title: KeyDetails
    description: Key details served from our internal DB
    type: object
    allOf:
      - properties:
          hash:
            type: string
            description: The key hash
          actor_id:
            type: string
            description: The actor id of the key
          expiration_date:
            type: string
            description: Date on which the api key will expire at 00.00 (optional)
            format: date
            pattern: '^\d{4}\-\d{2}-\d{2}'
          description:
            type: string
            description: Description for the key (optional)
            maxLength: 64
          creation_date:
            type: string
            description: DateTime on which the api key was created
            format: date
            pattern: '^\d{4}\-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z'
        required: [ "hash", "actor_id", "creation_date" ]
  KeyDetailsWithGatewayContext:
    title: KeyDetailsWithGatewayContext
    description: Detailed properties of a key, both from DB and the API Gateway
    type: object
    allOf:
      - properties:
          actor_id:
            type: string
            description: The actor id of the key
          policies:
            type: array
            items:
              type: string
            example: ["compliance-monitor-full-access", "routeplanner-full-access"]
          expiration_date:
            type: string
            description: Date on which the api key will expire at 00.00 (optional)
            format: date
            pattern: '^\d{4}\-\d{2}-\d{2}'
          quota:
            type: string
            description: The actor id of the key
          description:
            type: string
            description: Description for the key (optional)
            maxLength: 64
          creation_date:
            type: string
            description: DateTime on which the api key was created
            format: date
            pattern: '^\d{4}\-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z'
        required: [ "actor_id", "creation_date" ]