swagger: '2.0'
info:
  version: 1.0.0
  title: API Gateway API
  description: |
    This is where you can manage API Gateway using APIs
schemes:
  - https
  - http
consumes:
  - application/json
produces:
  - application/hal+json
  - application/problem+json
tags:
  - name: key
    description: Calls related to API keys
paths:
  /keys:
    post:
      operationId: create_key
      tags:
        - keys
      description: |
        Create a new API key
      consumes:
        - application/json
      parameters:
        - in: body
          name: request
          description: The details of the key being created.
          schema:
            type: object
            required:
              - actor_id
            properties:
              policies:
                type: array
                description: The access policies to give, leave empty for all
                items:
                  type: string
              actor_id:
                type: string
                description: The reference to the actor. In simple words, this is what binds an API key to a user/customer.
                pattern: '^.{1,16}'
      responses:
        '201':
          description: An API key has been created
          schema:
            allOf:
              - $ref: https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Resource.json#/definitions/Resource
              - type: object
                description: A key
                $ref: APIKey
        '400':
          $ref: "#/responses/BadRequest"
        '500':
          $ref: "#/responses/InternalServerError"
  /policies:
    get:
      operationId: list_policies
      tags:
        - policy
      description: |
        Get the list of available policies
      consumes:
        - application/json
      parameters: []
      responses:
        '200':
          description: list of available policies
          schema:
              type: array
              items:
                type: string
              example: ["compliance-monitor-full-access", "routeplanner-full-access"]
responses:
  BadRequest:
    description: Bad Request
    schema:
      $ref: "https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Problem.json#/definitions/Problem"
  InternalServerError:
    description: Internal Server Error
    schema:
      $ref: "https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Problem.json#/definitions/Problem"
definitions:
  Key:
    title: Key
    description: An API key
    type: object
    allOf:
      - $ref: https://s3.eu-central-1.amazonaws.com/de.company.info.prod.api.resource.bucket/schema/Resource.json#/definitions/Resource
      - properties:
          key:
            type: string
            description: The created API key which can be used to access APIs.
          hash:
            type: string
            description: The key hash. This is a unique identifier to each API key.
        required: [ "key", "hash" ]
