// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package key is a generated GoMock package.
package key

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetKeyByHash mocks base method.
func (m *MockRepositoryInterface) GetKeyByHash(hash string) (*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyByHash", hash)
	ret0, _ := ret[0].(*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyByHash indicates an expected call of GetKeyByHash.
func (mr *MockRepositoryInterfaceMockRecorder) GetKeyByHash(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyByHash", reflect.TypeOf((*MockRepositoryInterface)(nil).GetKeyByHash), hash)
}

// GetKeys mocks base method.
func (m *MockRepositoryInterface) GetKeys(input GetKeysInput) ([]*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", input)
	ret0, _ := ret[0].([]*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockRepositoryInterfaceMockRecorder) GetKeys(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockRepositoryInterface)(nil).GetKeys), input)
}

// StoreKey mocks base method.
func (m *MockRepositoryInterface) StoreKey(key Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreKey indicates an expected call of StoreKey.
func (mr *MockRepositoryInterfaceMockRecorder) StoreKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreKey", reflect.TypeOf((*MockRepositoryInterface)(nil).StoreKey), key)
}

// UpdateKeyByHash mocks base method.
func (m *MockRepositoryInterface) UpdateKeyByHash(hash string, values map[string]interface{}) (*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKeyByHash", hash, values)
	ret0, _ := ret[0].(*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateKeyByHash indicates an expected call of UpdateKeyByHash.
func (mr *MockRepositoryInterfaceMockRecorder) UpdateKeyByHash(hash, values interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKeyByHash", reflect.TypeOf((*MockRepositoryInterface)(nil).UpdateKeyByHash), hash, values)
}
