// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package key is a generated GoMock package.
package key

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tyk "gitlab.ci.fdmg.org/ci-api/tyk-sdk-go"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockClientInterface) AddKey(ctx context.Context, localVarOptionals *tyk.AddKeyOpts) (tyk.ApiModifyKeySuccess, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", ctx, localVarOptionals)
	ret0, _ := ret[0].(tyk.ApiModifyKeySuccess)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddKey indicates an expected call of AddKey.
func (mr *MockClientInterfaceMockRecorder) AddKey(ctx, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockClientInterface)(nil).AddKey), ctx, localVarOptionals)
}

// DeleteKey mocks base method.
func (m *MockClientInterface) DeleteKey(ctx context.Context, keyID string, localVarOptionals *tyk.DeleteKeyOpts) (tyk.ApiStatusMessage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", ctx, keyID, localVarOptionals)
	ret0, _ := ret[0].(tyk.ApiStatusMessage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockClientInterfaceMockRecorder) DeleteKey(ctx, keyID, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockClientInterface)(nil).DeleteKey), ctx, keyID, localVarOptionals)
}

// GetKey mocks base method.
func (m *MockClientInterface) GetKey(ctx context.Context, keyID string, localVarOptionals *tyk.GetKeyOpts) (tyk.SessionState, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, keyID, localVarOptionals)
	ret0, _ := ret[0].(tyk.SessionState)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetKey indicates an expected call of GetKey.
func (mr *MockClientInterfaceMockRecorder) GetKey(ctx, keyID, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockClientInterface)(nil).GetKey), ctx, keyID, localVarOptionals)
}

// UpdateKey mocks base method.
func (m *MockClientInterface) UpdateKey(ctx context.Context, keyID string, localVarOptionals *tyk.UpdateKeyOpts) (tyk.ApiModifyKeySuccess, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKey", ctx, keyID, localVarOptionals)
	ret0, _ := ret[0].(tyk.ApiModifyKeySuccess)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateKey indicates an expected call of UpdateKey.
func (mr *MockClientInterfaceMockRecorder) UpdateKey(ctx, keyID, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKey", reflect.TypeOf((*MockClientInterface)(nil).UpdateKey), ctx, keyID, localVarOptionals)
}
