// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package key is a generated GoMock package.
package key

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tyk "gitlab.ci.fdmg.org/datacluster/germany/api-gateway/tyk-sdk-go"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// AddKey mocks base method.
func (m *MockClientInterface) AddKey(ctx context.Context, localVarOptionals *tyk.AddKeyOpts) (tyk.ApiModifyKeySuccess, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddKey", ctx, localVarOptionals)
	ret0, _ := ret[0].(tyk.ApiModifyKeySuccess)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddKey indicates an expected call of AddKey.
func (mr *MockClientInterfaceMockRecorder) AddKey(ctx, localVarOptionals interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddKey", reflect.TypeOf((*MockClientInterface)(nil).AddKey), ctx, localVarOptionals)
}

// DeleteKey mocks base method.
func (m *MockClientInterface) DeleteKey(ctx context.Context, keyID string) (tyk.ApiStatusMessage, *http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKey", ctx, keyID)
	ret0, _ := ret[0].(tyk.ApiStatusMessage)
	ret1, _ := ret[1].(*http.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DeleteKey indicates an expected call of DeleteKey.
func (mr *MockClientInterfaceMockRecorder) DeleteKey(ctx, keyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKey", reflect.TypeOf((*MockClientInterface)(nil).DeleteKey), ctx, keyID)
}
