// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package key is a generated GoMock package.
package key

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetKeyByHash mocks base method.
func (m *MockRepositoryInterface) GetKeyByHash(hash string) (*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyByHash", hash)
	ret0, _ := ret[0].(*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeyByHash indicates an expected call of GetKeyByHash.
func (mr *MockRepositoryInterfaceMockRecorder) GetKeyByHash(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyByHash", reflect.TypeOf((*MockRepositoryInterface)(nil).GetKeyByHash), hash)
}

// GetKeysByActorID mocks base method.
func (m *MockRepositoryInterface) GetKeysByActorID(actorID string) ([]*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysByActorID", actorID)
	ret0, _ := ret[0].([]*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysByActorID indicates an expected call of GetKeysByActorID.
func (mr *MockRepositoryInterfaceMockRecorder) GetKeysByActorID(actorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysByActorID", reflect.TypeOf((*MockRepositoryInterface)(nil).GetKeysByActorID), actorID)
}

// ListKeys mocks base method.
func (m *MockRepositoryInterface) ListKeys() ([]*Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKeys")
	ret0, _ := ret[0].([]*Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKeys indicates an expected call of ListKeys.
func (mr *MockRepositoryInterfaceMockRecorder) ListKeys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKeys", reflect.TypeOf((*MockRepositoryInterface)(nil).ListKeys))
}

// StoreKey mocks base method.
func (m *MockRepositoryInterface) StoreKey(key Key) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreKey indicates an expected call of StoreKey.
func (mr *MockRepositoryInterfaceMockRecorder) StoreKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreKey", reflect.TypeOf((*MockRepositoryInterface)(nil).StoreKey), key)
}
