// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock.go -package=customers
//

// Package customers is a generated GoMock package.
package customers

import (
	context "context"
	reflect "reflect"

	"gitlab.ci.fdmg.org/ci-api/admin-api/internal/handler/v2/policies"
	customer "gitlab.ci.fdmg.org/ci-api/go-pkgs/customer"
	gomock "go.uber.org/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAccount mocks base method.
func (m *MockServiceInterface) GetAccount(ctx context.Context, customerID, accountID string) (*customer.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", ctx, customerID, accountID)
	ret0, _ := ret[0].(*customer.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockServiceInterfaceMockRecorder) GetAccount(ctx, customerID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockServiceInterface)(nil).GetAccount), ctx, customerID, accountID)
}

// GetAccountCount mocks base method.
func (m *MockServiceInterface) GetAccountCount(ctx context.Context, customerID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountCount", ctx, customerID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountCount indicates an expected call of GetAccountCount.
func (mr *MockServiceInterfaceMockRecorder) GetAccountCount(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountCount", reflect.TypeOf((*MockServiceInterface)(nil).GetAccountCount), ctx, customerID)
}

// GetAccountExtended mocks base method.
func (m *MockServiceInterface) GetAccountExtended(ctx context.Context, customerID, accountID string) (*ExtendedAccountResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountExtended", ctx, customerID, accountID)
	ret0, _ := ret[0].(*ExtendedAccountResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountExtended indicates an expected call of GetAccountExtended.
func (mr *MockServiceInterfaceMockRecorder) GetAccountExtended(ctx, customerID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountExtended", reflect.TypeOf((*MockServiceInterface)(nil).GetAccountExtended), ctx, customerID, accountID)
}

// GetCurrentAPIKeyCount mocks base method.
func (m *MockServiceInterface) GetCurrentAPIKeyCount(customerID, accountID string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentAPIKeyCount", customerID, accountID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentAPIKeyCount indicates an expected call of GetCurrentAPIKeyCount.
func (mr *MockServiceInterfaceMockRecorder) GetCurrentAPIKeyCount(customerID, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentAPIKeyCount", reflect.TypeOf((*MockServiceInterface)(nil).GetCurrentAPIKeyCount), customerID, accountID)
}

// GetCustomer mocks base method.
func (m *MockServiceInterface) GetCustomer(ctx context.Context, id string) (*CustomerResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomer", ctx, id)
	ret0, _ := ret[0].(*CustomerResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomer indicates an expected call of GetCustomer.
func (mr *MockServiceInterfaceMockRecorder) GetCustomer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomer", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomer), ctx, id)
}

// GetCustomersCount mocks base method.
func (m *MockServiceInterface) GetCustomersCount(ctx context.Context, params customer.ListParams) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersCount", ctx, params)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersCount indicates an expected call of GetCustomersCount.
func (mr *MockServiceInterfaceMockRecorder) GetCustomersCount(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersCount", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomersCount), ctx, params)
}

// GetCustomersPaginated mocks base method.
func (m *MockServiceInterface) GetCustomersPaginated(ctx context.Context, params customer.ListParams) ([]*CustomerResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCustomersPaginated", ctx, params)
	ret0, _ := ret[0].([]*CustomerResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCustomersPaginated indicates an expected call of GetCustomersPaginated.
func (mr *MockServiceInterfaceMockRecorder) GetCustomersPaginated(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCustomersPaginated", reflect.TypeOf((*MockServiceInterface)(nil).GetCustomersPaginated), ctx, params)
}

// GetPricingPlanQuotaPolicy mocks base method.
func (m *MockServiceInterface) GetPricingPlanQuotaPolicy(pricingPlanID string) (policies.Policy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPricingPlanQuotaPolicy", pricingPlanID)
	ret0, _ := ret[0].(policies.Policy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPricingPlanQuotaPolicy indicates an expected call of GetPricingPlanQuotaPolicy.
func (mr *MockServiceInterfaceMockRecorder) GetPricingPlanQuotaPolicy(pricingPlanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPricingPlanQuotaPolicy", reflect.TypeOf((*MockServiceInterface)(nil).GetPricingPlanQuotaPolicy), pricingPlanID)
}

// GetSubscription mocks base method.
func (m *MockServiceInterface) GetSubscription(ctx context.Context, customerID, accountID, pricingPlanID string) (Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", ctx, customerID, accountID, pricingPlanID)
	ret0, _ := ret[0].(Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockServiceInterfaceMockRecorder) GetSubscription(ctx, customerID, accountID, pricingPlanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockServiceInterface)(nil).GetSubscription), ctx, customerID, accountID, pricingPlanID)
}

// ListAccounts mocks base method.
func (m *MockServiceInterface) ListAccounts(ctx context.Context, customerID string) ([]customer.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccounts", ctx, customerID)
	ret0, _ := ret[0].([]customer.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccounts indicates an expected call of ListAccounts.
func (mr *MockServiceInterfaceMockRecorder) ListAccounts(ctx, customerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccounts", reflect.TypeOf((*MockServiceInterface)(nil).ListAccounts), ctx, customerID)
}

// ListAccountsPaginated mocks base method.
func (m *MockServiceInterface) ListAccountsPaginated(ctx context.Context, customerID string, first, max int) ([]*AccountResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAccountsPaginated", ctx, customerID, first, max)
	ret0, _ := ret[0].([]*AccountResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAccountsPaginated indicates an expected call of ListAccountsPaginated.
func (mr *MockServiceInterfaceMockRecorder) ListAccountsPaginated(ctx, customerID, first, max any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAccountsPaginated", reflect.TypeOf((*MockServiceInterface)(nil).ListAccountsPaginated), ctx, customerID, first, max)
}

// UpdateAccount mocks base method.
func (m *MockServiceInterface) UpdateAccount(ctx context.Context, customerUpdate customer.CustomerUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, customerUpdate)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockServiceInterfaceMockRecorder) UpdateAccount(ctx, customerUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockServiceInterface)(nil).UpdateAccount), ctx, customerUpdate)
}
